trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - src/modules/*
  
pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev
    jobs:
      - job: BicepModulesDeploy
        displayName: Bicep Modules Deploy
        steps:
          - checkout: self
            persistCredentials: true          
          
          - powershell: |
              cd $(Build.SourcesDirectory)

              Get-ChildItem -Recurse

              git status
              git describe --tags 

              Write-Host "Validate version file"
              $lastTag = git describe --tags --abbrev=0  
              

              
              (git diff --name-only $lastTag $(Build.SourceBranch))
              $versionFile = (git diff --name-only $lastTag $(Build.SourceBranch)) -match "/version.json"          
              
              if($versionFile.Count -gt 1){ 
                Write-Error "More than one version file updated"
              }elseif($null -eq $versionFile -or $versionFile.Count -eq 0 -or $versionFile -eq $false){
                Write-Error "No version files were updated"
              }
    
              # $versionFile = Get-Content -Raw -Path $versionFile | ConvertFrom-Json
    
              # Write-Host "Module changed: '$($versionFile.module)'"
              # Write-Host "Module version: '$($versionFile.version)'"
              
              # Write-Output "bicepModuleVersion=$($versionFile.version)" >> $env:GITHUB_ENV
              # Write-Output "bicepModuleName=$($versionFile.module)" >> $env:GITHUB_ENV
          
          - task: AzureCLI@2
            displayName: Deploy bicep modules
            enabled: false
            inputs:              
              azureSubscription: 'ServicePrincipal'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "Loading existing modules..."
                               
                $acrId = "brmodexpcr001.azurecr.io"
                
                $coreModules = "$(Build.SourcesDirectory)/src/modules"
                
                $versionFiles = Get-ChildItem $coreModules -Recurse -Filter "version.json" | Select-Object FullName 
                
                foreach ($versionFilePath in $versionFiles) {
                    $versionFile = Get-Content -Raw -Path $versionFilePath.FullName | ConvertFrom-Json
                
                    Write-Host "Module: '$($versionFile.module)'"
                    Write-Host "Module version: '$($versionFile.version)'"
                
                    $bicepModule = $versionFilePath.FullName.Replace("version.json", "main.bicep")
                    
                    az bicep publish --file $bicepModule --target "br:$acrId/bicep/modules/$($versionFile.module):v$($versionFile.version)"
                }
