name: CI

on:
  push:
    branches: [ "feature/*" ]  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        shell: pwsh
        run: |
          
          cd $env:GITHUB_WORKSPACE

          # Validate version file
          $lastTag = git describe --tags --abbrev=0  
          $versionFile = (git diff --name-only $lastTag $env:GITHUB_REF) -match "/version.json"

          if($versionFile.Count -gt 1){ 
            Write-Host "More than one version file updated"
            exit 1
          }elseif($null -eq $versionFile -or $versionFile.Count -eq 0){
            Write-Host "No version files were updated"
            # exit 1
          }

          $versionFile = Get-Content -Raw -Path $versionFile | ConvertFrom-Json

          Write-Host "Module changed: '$versionFile.module'"
          Write-Host "Module version: '$versionFile.version'"
          
          Write-Output "bicepModuleVersion=$($versionFile.version)" >> $env:GITHUB_ENV
          Write-Output "bicepModuleName=$($versionFile.module)" >> $env:GITHUB_ENV
      
      - name: Validate changed modules
        shell: pwsh
        run: |
          Write-Host "Obtaining changed files..."
          $lastTag = git describe --tags --abbrev=0  
          $changedFiles = (git diff --name-only $lastTag $env:GITHUB_REF) 

          Write-Host $changedFiles

          foreach($file in $changedFiles){
            Write-Host "Validating '$file'"
            if(($file -notcontains $env:bicepModuleName) -and ($file -contains "src/modules"))
            {
              Write-Error "Error: Identified changes in a different module"          
            }
          }

      - name: Test
        shell: pwsh
        run: |
          
          $tagVersion = "$env:bicepModuleName-$env:bicepModuleVersion"
          Write-Host $tagVersion

          cd $env:GITHUB_WORKSPACE

          $existingTag = git tag -l $tagVersion

          if($existingTag){
            Write-Host "Version '$tagVersion' already exist"
            exit 1
          }
            
          Write-Host "Generating tag '$tagVersion'"
          git tag $tagVersion
          git push --tags