name: CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        shell: pwsh
        run: |
          $versionFile = (git diff --name-only main) -match "/version.json"
          
          if($versionFile.Count -gt 1){ 
            Write-Host "More than one version file updated"
            exit 1
          }

          $versionFile = Get-Content -Raw -Path $versionFile | ConvertFrom-Json

          Write-Host $versionFile.version
          Write-Host $versionFile.module

      # - name: Set SemVer
      #   run: |
      #     $version = (Get-Content -Raw -Path 'version.json' | ConvertFrom-Json).version
      #     echo "version=$(echo $version | cut -c 1-6)" >> $env:GITHUB_ENV


      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:          
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"      
          
          inlineScript: |
            #   Write-Host $env:GITHUB_WORKSPACE

            Invoke-Expression -Command $env:GITHUB_WORKSPACE/pipelines/common/scripts/tests/PesterRunner.ps1


